// Generated by CoffeeScript 1.12.6
(function() {
  var config;

  config = require('./config.data.js');

  require('angular').module('config', []).config([
    '$sceDelegateProvider', '$httpProvider', function($sceDelegateProvider, $httpProvider) {
      return $sceDelegateProvider.resourceUrlWhitelist(['self', 'http*://*.soundcloud.com/**', 'http*://soundcloud.com/**', 'http*://vimeo.com/**', 'http*://*.vimeo.com/**', 'http*://*.youtube.com/**', 'http*://youtube.com/**', 'http*://*.youtu.be/**', 'http*://youtu.be/**', 'http*://google.com/**', 'http*://*.google.com/**', 'http*://*.marionrampal.com/**']);
    }
  ]).factory('Config', [
    '$location', function($location) {
      var local, msg;
      local = /(\.local|192\.168\.1\.51)$/.test($location.host());
      if (local !== config.local) {
        msg = 'wrong config file!';
        console.log(msg);
      }
      config.ajaxHost = function(uri) {
        if (local) {
          return "http://ajax.marionrampal.local" + "/" + uri;
        }
        return "http://ajax.marionrampal.com" + "/" + uri;
      };
      return config;
    }
  ]).run(['Config', function(config) {}]);

  module.exports = 'config';

}).call(this);

//# sourceMappingURL=config.js.map
