// Generated by CoffeeScript 2.6.1
(function() {
  module.exports = 'contactForm';

  require('angular').module('contactForm', [require('./config')]).directive("contactForm", [
    function() {
      return {
        restrict: 'AE',
        templateUrl: 'templates/contact.html',
        scope: false,
        replace: true,
        controller: [
          '$scope',
          '$http',
          "$location",
          "Config",
          function($scope,
          $http,
          $location,
          Config) {
            $scope.msg = {};
            return $scope.submit = function() {
              $scope.msg;
              $scope.msg.error = null;
              $scope.msg.result = null;
              $scope.submitting = true;
              return $http.post(Config.ajaxHost('contact'),
          $scope.msg).then(function(res) {
                $scope.submitting = false;
                $scope.msg = {};
                $scope.msg.error = false;
                $scope.msg.result = res.data.txt;
                $scope.contactForm.$setPristine();
                return $scope.contactForm.$setUntouched();
              },
          function(res) {
                
                // we reset to pristine  every time the user submit EVEN IF WE DON'T RESET THE CONTENT (in case of error)
                $scope.submitting = false;
                $scope.contactForm.$setPristine();
                $scope.contactForm.$setUntouched();
                $scope.msg.error = true;
                return $scope.msg.result = "Le message n'a pas pu être envoyé: " + res.data.txt;
              });
            };
          }
        ]
      };
    }
  ]).controller("formCtrl", [
    '$scope',
    function($scope) {
      return $scope.focused = false;
    }
  ]);

}).call(this);

//# sourceMappingURL=contact.form.js.map
