// Generated by CoffeeScript 2.6.1
(function() {
  var marked, registerNbrOfSections;

  module.exports = 'markedConfig';

  registerNbrOfSections = require('./marked.utils');

  marked = require('marked');

  require('angular').module('markedConfig', [require('angular-marked'), require('angular-ui-bootstrap'), require('./oEmbed'), require('./sections'), require('./resource.file')]).config([
    'markedProvider',
    'EmbedUrl',
    'ResourceFile',
    function(markedProvider,
    EmbedUrl,
    ResourceFile) {
      console.log("marked defaults");
      console.log(marked.defaults);
      markedProvider.setOptions(marked.defaults);
      return markedProvider.setRenderer(marked.defaults.renderer);
    }
  ]).run([
    'Sections',
    function(Sections) {
      return registerNbrOfSections(Sections.nbrOfSectionsToLoad);
    }
  ]).directive('carouselCtrl', function() {
    return {
      template: "<div ng-transclude></div>",
      transclude: true,
      scope: {},
      controller: [
        function() {
          this.active = 0;
        }
      ],
      controllerAs: 'cc',
      link: function(scope, element, attrs) {
        var elt, i, j, listitem, ref, results, slides;
        elt = element[0];
        slides = elt.querySelectorAll("div[uib-slide]");
        console.log(elt);
        console.log(slides);
        results = [];
        for (i = j = 0, ref = slides.length - 1; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
          listitem = slides[i];
          listitem.setAttribute("index", i);
          console.log("item" + i);
          results.push(console.log(listitem));
        }
        return results;
      }
    };
  });

}).call(this);

//# sourceMappingURL=marked.config.js.map
