// Generated by CoffeeScript 2.4.1
(function() {
  var baseParams, makeMenu;

  module.exports = 'menu';

  baseParams = {
    windowClass: 'main-menu',
    backdrop: true,
    controller: [
      '$scope',
      '$uibModalInstance',
      'Sections',
      'State',
      function($scope,
      $uibModalInstance,
      Sections,
      State) {
        //on opening the menu we navigate back to the home state, so that all "pages" are available.
        State.home();
        this.title = 'Menu';
        this.ok = function(e) {
          $uibModalInstance.close();
          if (e) {
            return e.stopPropagation();
          }
        };
        this.cancel = function(e) {
          $uibModalInstance.dismiss();
          if (e) {
            return e.stopPropagation();
          }
        };
        this.sections = Sections.data;
        return this;
      }
    ],
    controllerAs: 'MenuCtrl'
  };

  makeMenu = function(params) { //params is an object must include placement and template or templateUrl 
    return function($aside) {
      var menu;
      menu = null;
      return {
        open: function() {
          if (menu !== null) {
            console.log("trying to open main menu while it already is");
            return menu;
          }
          menu = $aside.open({...baseParams, ...params});
          menu.result.then((function() {
            console.log('Closed menu');
            return menu = null;
          }), (function() {
            console.log('Dismissed menu');
            return menu = null;
          }));
          return menu.result;
        },
        isOpen: function() {
          return menu !== null;
        },
        close: function() {
          if (menu === null) {
            console.log("trying to close main menu while not open");
            return;
          }
          return menu.close();
        },
        dismiss: function() {
          if (menu === null) {
            console.log("trying to dismiss main menu while not open");
            return;
          }
          return menu.dismiss();
        }
      };
    };
  };

  require('angular').module('menu', [require('angular-aside'), require('./states')]).factory('Menu', [
    '$aside',
    makeMenu({
      placement: 'right',
      templateUrl: 'templates/menu.html'
    })
  ]).directive("mainMenu", [
    'Menu',
    function(Menu) {
      return {
        restrict: 'A',
        scope: false,
        replace: false,
        link: function(scope,
    elt,
    attrs) {
          return elt.on('click',
    function() {
            return Menu.open().then((function() {
              return console.log(' Closed menu 2');
            }),
    function() {
              return console.log(' Dismissed menu 2');
            });
          });
        }
      };
    }
  ]).factory('GetInTouch', [
    '$aside',
    makeMenu({
      placement: 'left',
      template: '<marked compile=true filename="getInTouch"></marked>'
    })
  ]).directive("getInTouch", [
    'GetInTouch',
    function(Menu) {
      return {
        restrict: 'A',
        scope: false,
        replace: false,
        link: function(scope,
    elt,
    attrs) {
          return elt.on('click',
    function() {
            return Menu.open().then((function() {
              return console.log(' Closed get in touch');
            }),
    function() {
              return console.log(' Dismissed get in touch');
            });
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=menu.js.map
