// Generated by CoffeeScript 1.12.6
(function() {
  module.exports = 'mobile.expand';

  require('angular').module('mobile.expand', [require('angular-aside')]).factory('MobileExpand', [
    '$uibModal', function($uibModal) {
      var window;
      window = null;
      return {
        open: function(content, popupLinks) {
          if (window !== null) {
            console.log("trying to open mobile expand window while it already is");
            return window;
          }
          window = $uibModal.open({
            templateUrl: '/templates/mobileExpand.html',
            backdrop: true,
            size: 'fs',
            controller: [
              '$scope', '$uibModalInstance', 'Sections', function($scope, $uibModalInstance, Sections) {
                this.title = 'Mobile Content';
                this.ok = function(e) {
                  $uibModalInstance.close();
                  if (e) {
                    return e.stopPropagation();
                  }
                };
                this.cancel = function(e) {
                  $uibModalInstance.dismiss();
                  if (e) {
                    return e.stopPropagation();
                  }
                };
                $scope.content = content;
                $scope.popupLinks = popupLinks;
                return this;
              }
            ],
            controllerAs: 'MobileContentCtrl',
            windowTopClass: 'windowTopClass',
            windowClass: 'windowClass'
          });
          window.result.then((function() {
            console.log('Closed window');
            return window = null;
          }), (function() {
            console.log('Dismissed window');
            return window = null;
          }));
          return window.result;
        },
        isOpen: function() {
          return window !== null;
        },
        close: function() {
          if (window === null) {
            console.log("trying to close main window while not open");
            return;
          }
          return window.close();
        },
        dismiss: function() {
          if (window === null) {
            console.log("trying to dismiss main window while not open");
            return;
          }
          return window.dismiss();
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=mobile.expand.js.map
