// Generated by CoffeeScript 1.12.6
(function() {
  var resourceUrl;

  module.exports = 'resourceFile';

  resourceUrl = function(url, title, text) {
    var escape, html, resourceFile;
    escape = function(str) {
      switch (str) {
        case "\n":
          return "\\n";
        case "\"":
          return "\\&quot;";
      }
      return str;
    };
    resourceFile = url.match(/\.([^.]+)$/);
    if (resourceFile) {
      switch (resourceFile[1]) {
        case 'md':
          if (text == null) {
            text = "";
          }
          if (title == null) {
            title = "";
          }
          html = '<include-markup content="{&quot;filename&quot;:&quot;' + url + '&quot;,&quot;caption&quot;:&quot;' + title + '&quot;,&quot;chapeau&quot;:&quot;' + text.replace(/[\n\\\"]/g, escape) + '&quot;,' + '&quot;inline&quot;:' + true + '}" popup-links="popupLinks"></include-markup>';
          return {
            html: html
          };
        case 'i18n':
          url = url.substr(0, url.length(-5));
          if (text == null) {
            text = "";
          }
          if (title == null) {
            title = "";
          }
          html = '<include-markup content="{&quot;filename&quot;:&quot;' + url + '&quot;,&quot;caption&quot;:&quot;' + title + '&quot;,&quot;chapeau&quot;:&quot;' + text.replace(/[\n\\\"]/g, escape) + '&quot;,' + '&quot;inline&quot;:' + true + '}" popup-links="popupLinks"></include-markup>';
      }
    }
    return false;
  };

  require('angular').module('resourceFile', ['config']).constant('ResourceFile', resourceUrl);

}).call(this);

//# sourceMappingURL=resource.file.js.map
