// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = 'resourceFile';

  require('angular').module('resourceFile', ['config']).constant('ResourceFile', require('./resourceFile'));

}).call(this);

//# sourceMappingURL=resource.file.js.map
