// Generated by CoffeeScript 2.6.1
(function() {
  module.exports = 'section';

  require('angular').module('section', [require('./sections.ng'), require('./states')]).component('section', {
    template: '<ng-transclude ng-if="!$sc.empty"></ng-transclude>',
    transclude: true,
    bindings: {
      section: '<',
      sectionData: '@'
    },
    controller: [
      'State',
      'Sections',
      '$scope',
      function(State,
      Sections,
      $scope) {
        this.empty = false;
        this.$onInit = () => {
          var e;
          if (this.section == null) {
            try {
              this.section = JSON.parse(this.sectionData);
            } catch (error) {
              e = error;
              console.log("data for the section is not well formed: " + e.toString());
              console.log(this.sectionData);
              return;
            }
            this.section = Sections.registerSectionData(this.section); //if this.section already exists, then it was already added
          }
          if (this.section.emptyEvent) { //this is used for calendars only for now, if if it's empty hide the section
            if (!State.getAllowEdit()) {
              $scope.$on(this.section.emptyEvent,
      (e,
      args) => {
                var next,
      previous;
                this.empty = true;
                next = this.section.pages[this.section.pages.length - 1].next;
                if ((previous = this.section.pages[0].previous) != null) {
                  previous.next = next;
                }
                if (next != null) {
                  return next.previous = previous;
                }
              });
            }
          }
        };
        this.$onDestroy = () => {
          return this.section.destroy();
        };
      }
    ],
    controllerAs: '$sc'
  });

}).call(this);

//# sourceMappingURL=section.js.map
