// Generated by CoffeeScript 2.6.1
(function() {
  var moment;

  module.exports = 'songkick';

  moment = require('moment');

  // require 'moment/locale/fr'
  // require 'moment-timezone' 
  // striptags = require('striptags')

  // getZoneFromOffset = (offsetString) -> moment.tz.names().find((tz) -> moment.tz(tz).format('Z') == offsetString)
  require('angular').module('songkick', ['config', require('./language.picker')]).factory('Songkick', [
    'Config',
    '$http',
    'Locale',
    function(Config,
    $http,
    Locale) {
      var calendars,
    errCount,
    key,
    loadCalendar,
    noop,
    setLocalDateTime;
      key = Config.songkickApikey;
      calendars = {};
      errCount = 0;
      noop = {
        then: function(callback) {
          console.log("calendar not configured for songkick");
          return callback([]);
        }
      };
      setLocalDateTime = function(event) {
        if (!event.start.dateTime) {
          return event.localDateTime = moment(event.start.date).format("l");
        } else if (event.start.timeZone !== void 0) {
          return event.localDateTime = moment(event.start.dateTime).tz(event.start.timeZone).format("lll");
        } else {
          return event.localDateTime = moment(event.start.dateTime).format("lll");
        }
      };
      loadCalendar = function(id) {
        var listEvents;
        listEvents = 'https://api.songkick.com/api/3.0/artists/' + id + '/calendar.json?apikey=' + key;
        return calendars[id] = $http.get(listEvents).then(function(response) {
          var events;
          events = response.data.resultsPage.results.event;
          console.log(events);
          return events.map(function(event) {
            event.start.dateTime = event.start.datetime;
            if (event.end != null) {
              event.end.dateTime = event.end.datetime;
            } else {
              event.end = event.start;
            }
            return {
              summary: event.displayName,
              location: `${event.venue.displayName}, ${event.location.city}`,
              description: event.uri,
              start: event.start,
              end: event.end,
              lat: event.venue.lat,
              lng: event.venue.lng
            };
          });
        // timezone:  getZoneFromOffset(offsetString)
        }).catch(function(response) {
          console.log('songkick request failed: ' + response.message + ', status: ' + response.status);
          if (response.status === 404) {
            return noop;
          }
          // we "eat" the error at some point, won't retry to access the calendar (note it is a global err count, not per calendar):
          if (errCount++ < 3) {
            console.log("calendar error number " + errCount);
            return noop;
          }
          return noop;
        });
      };
      Locale.onChange(function() {
        var calId,
    calendar,
    event,
    results;
        moment.locale(Locale.get().language);
        results = [];
        for (calId in calendars) {
          calendar = calendars[calId];
          results.push((function() {
            var i,
    len,
    results1;
            results1 = [];
            for (i = 0, len = calendar.length; i < len; i++) {
              event = calendar[i];
              results1.push(setLocalDateTime(event));
            }
            return results1;
          })());
        }
        return results;
      });
      return function(calId) {
        var id,
    ref,
    ref1;
        if (!Config.songkickApikey) {
          return noop;
        }
        id = (ref = calId.songkickId) != null ? ref : (calId.musicBrainzId != null ? "mbid:" + calId.musicBrainzId : null);
        if (id == null) {
          return noop;
        }
        return (ref1 = calendars[id]) != null ? ref1 : loadCalendar(id);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=songkick.js.map
